### ISSUE TITLE
Include symfony/yaml package to allow yaml parsing

### ISSUE THREAD

**Issue by caseyfw** [Codegyre/Robo#181]
It would be nice if the Robo phar included the symfony/yaml package so tasks could parse a yaml file for config items.

This is useful for build/deployment tasks that require a bunch of different configuration that can be transported in a yaml file.

**Comment by caseyfw** [comment]
We're using Robo to build a Drupal project, and part of our build reads a bunch of config from a yaml file and sets the corresponding value in Drupal using `drush cset`.

Our temporary solution until the symfony/yaml package is included in the robo phar relies on a `composer install` having already been done in the project directory. This way, those extra packages can be included for autoloading:

```php
public function buildConfigure() {
  // Assuming deps have been pulled, load them.
  if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require_once __DIR__ . '/vendor/autoload.php';
  }
  if (file_exists($this->config_file)) {
    $raw = file_get_contents($this->config_file);
    $yaml = Yaml::parse($raw, TRUE, FALSE);
    $task_stack = $this->taskExecStack();
    foreach ($yaml['drupal_config'] as $drupal_config_name => $drupal_config_items) {
      foreach ($drupal_config_items as $key => $value) {
        $task_stack->exec($this->drush_cmd . ' cset ' . $drupal_config_name .
          ' ' . $key . ' "' . $value . '" -y');
      }
    }
    $task_stack->printed(FALSE)->stopOnFail(TRUE)->run();
    $this->say('Site configuration imported');
  }
  else {
    $this->say($this->config_file . ' file not found');
  }
}
```

**Comment by boedah** [comment]
From my opinion projects should include additional dependencies themselves as Robo should not include dependencies it is not using itself.

**Comment by caseyfw** [comment]
What do you think about a getConfig() task or something along those lines? We could even get more extreme and use the symfony/config package...

**Comment by boedah** [comment]
Talked about this with @DavertMik, and I think he is not a big fan of this (see comments from https://github.com/Codegyre/Robo/issues/41#issuecomment-46954307 on).
We also reverted to using PHP instead of YAML for config files.

Nevertheless, I would find a config system similar to ant/phing, where you can use config properties of a global config file in local config files easily appealing...

**Comment by caseyfw** [comment]
I can see the logic in this. YAML does add needless overhead when we can achieve what we want with plain old php. I guess I was perhaps a bit too "all aboard the YAML train".

**Comment by c33s** [comment]
including yaml support will really help and enhance the developer experience. many developers, who maybe are not that experienced  and just want to use this nice tool and not having to "compile/build" it before, should have the most used tools onboard.

why argue to switch to php config, if there is a yaml config? if i want to read and write my travis file? or a symfony config file? a r10k config file? and so on. all this files are often found in the domain of robo.
 
i think the argument "robo don't use it, so it should not be shipped" is not true, .semver is also not used in robo but it is really helpful for managing my semver file.
do not argue against something just because you don't use it, not for the minimal increase of 100kb of a phar file.

so +1 for adding yaml support and tasks in robo, i would love to load my symfony parameters.yml file in robo.

**Comment by caseyfw** [comment]
I've come around to not including yaml support in the base package. It's
easy enough to add it yourself by requiring it. We did this for a bunch of
robo build scripts that run on our CI.

**Comment by greg-1-anderson** [comment]
Another option is to `composer global require codegyre/robo`, and also use `composer global require` for yaml parsers or whatever else you need. Then, if you use the standalone Robo script feature (#285), your scripts will have access to anything in the Composer global autoloader.

**Comment by c33s** [comment]
please reconsider this.

the main reasons for including it:
- small footprint
- yaml is widespread in the php world
- robo should not need to include the vendor of the project (this nearly always get you in the conflicting dependency hell)
- if someone like me is building its own version, the build chain is not as good as the official one. so builds are out of date, couldn't  be downloaded as easy (must be deployed and hosted somewhere). it is a very big effort to maintain a custom `robo.phar` build which many small companies couldn't handle. 
- it hurts really no one, to include it. people who don't like yaml won't even recocnize it.

i came across some small companies where robo was rejected just because of this. they felt it like to have build their own phpunit.phar to include such a basic thing as functional testing. i argued with "build it yourself"... but people want things out of the box (in this case me too) and they switched to tools which are able to handle this out of the box (i still would prefer robo). also using puppet with hiera data, i would also love to use robo there but as i said, i can't make it to handle the build chain myself.

so i kindly ask you to reconsider this. don't be so strict for such a small thing. i am not asking for the inclusion of the whole symfony framework.

**Comment by greg-1-anderson** [comment]
Note that Robo now depends on [grasmash/yaml-expander](https://github.com/consolidation/Robo/blob/a5dfd6abf10f8697dde812f29eed6250e30a3a60/composer.json#L32) and [symfony/yml](https://github.com/consolidation/Robo/blob/a5dfd6abf10f8697dde812f29eed6250e30a3a60/composer.lock#L989) is therefore also required as a result.

You might also be interested in the [documentation on Robo Configuration](https://github.com/consolidation/Robo/blob/a5dfd6abf10f8697dde812f29eed6250e30a3a60/docs/getting-started.md#configuration).

Perhaps you'd be interested in a stable release?

Please test and see if it meets your use-case.

**Comment by c33s** [comment]
@greg-1-anderson a w e s o m e! 
thanks for showing me the links. havn't thought that yaml silently made it in.
