### ISSUE TITLE
Drop support for PHP 5.4

### ISSUE THREAD

**Issue by DavertMik** [Codegyre/Robo#259]
We are planning to drop support for PHP 5.4 in Robo 1.0
Does anyone have objections?

**Comment by burzum** [comment]
No, just drop it! :+1:

I don't think php version that have reached their EOL should be dragged along the path.

![php Versions](http://cdn.websharks-inc.com/zencache/uploads/2015/11/currently-supported-php-versions.png)

**Comment by boedah** [comment]
:+1:

**Comment by Falc** [comment]
:+1: 

Major PHP frameworks are already requiring PHP >= 5.5.
Related: https://github.com/piwik/piwik/issues/8156

**Comment by greg-1-anderson** [comment]
A strongly related issue is, what to do with Symfony 2.x support? Right now, the Robo 0.x line claims to support Symfony 2, but this is untested. This makes it difficult to respond if folks report issues.

What I would recommend is:

1. Make a Robo 1.x branch.  Remove support for Symfony 3 there, and tag Robo 1.0.
2. On master, remove support for Symfony 2 and php 5.4.

Then, even if we do not want to continue support for Symfony 2, it would be helpful to have a branch that is unambiguously for Symfony 2.

**Comment by dustinleblanc** [comment]
I concur, drop it like it's hot. PHP is moving and I for one like to keep with it.

**Comment by greg-1-anderson** [comment]
PHP 5.4 support already removed in #284, which hopefully will be ready to merge shortly.

**Comment by greg-1-anderson** [comment]
This has been done.

**Comment by lpalgarvio** [comment]
Dropping support for PHP versions "just because" is not wise, if not reckless.

Some facts:
- [Symphony 3.2](https://symfony.com/doc/3.2/reference/requirements.html) requires PHP 5.5.9, has no mention of recommendations
- [Symphony 2.8](https://symfony.com/doc/2.8/reference/requirements.html) requires PHP 5.3.9, has no mention of recommendations
- [Drupal 8](https://www.drupal.org/docs/7/system-requirements/php) .xrequires PHP 5.5.9, recommends 5.6 to 7.x AND requires Symphony 2.8
- [Drupal 7.x](https://www.drupal.org/docs/7/system-requirements/php) requires PHP 5.2.5, recommends 5.4 to 5.6
- [Drupal 6.x](https://api.drupal.org/api/drupal/modules%21system%21system.module/constant/DRUPAL_MINIMUM_PHP/6.x) requires PHP 4.3.5, recommends 5.3 (deprecated only last year)
- [Wordpress 4.7.x](https://wordpress.org/about/requirements/) requires PHP 5.2.4, recommends 7.x

What is the technical justification for implying a PHP version higher than 5.4?
I understand PHP 5.4 as minimum version is interesting because you can use for example the new array notation `$array = [];` vs `$array = array();`.

May you reconsider this change and allow PHP 5.4?
And yes, Robo 1.0.6 is currently working fine with Symphony 2.8. In fact it is forced to, because Drupal 8 requires Symphony 2.8.

I hope you find good judgement.

**Comment by dustinleblanc** [comment]
This isn't just because. PHP eol'd 5.4 quite a while ago and maintaining backwards compatibility for dead software is like a boat anchor tied to your Tesla. At this point almost all distros ship with 5.5+ which is in itself quite long in the tooth. Robo is positioned as a modern task runner. Stifling progress for backwards compatibility is the antithesis of modern.

D7+ runs fine on current PHP versions, as do most symfony versions. Drupal 6 is deprecated and not worth consideration. I'm waiting for the day we can deprecate all of PHP 5.

If you need support for 5.4-, use an older release of robo, fork it and backport changes you need.

**Comment by greg-1-anderson** [comment]
You don't need to run Robo on your production server, only on your build server. Getting php 5.5 (which is itself already EOL) should not be difficult.

Some minor corrections.

- Drupal 8 fully supports php 7. The issue you link to is closed, fixed.
- Drupal 6 is EOL, not deprecated.

If you have a strong use-case for running Robo on a php 5.4 system, are you offering to be the php 5.4 maintainer? If so, it would be up to @DavertMik to decide whether or not to allow that. The main challenges faced with supporting php 5.4 is ensuring that all of our dependencies still support php 5.4. All of them. I know that the key dependencies, such as Symfony 2.x, Annotated Command and Output Formatter support php 5.4 (Drush 8 still supports php 5.4, for the reasons you mention), so it might not be impossible. I'm just not sure what the remediation would be if you found a component that didn't support 5.4 any longer in the version we're currently using. We're unlikely to want to support split versions just to carry 5.4 forward.

The first step would be to try Robo on php 5.4 and see if you can get it to work.

**Comment by lpalgarvio** [comment]
Currently busy with wrapping up a project, but I'll get back to you and testing as soon as I get a chance.
