### ISSUE TITLE
Autoload composer autoload.php from robo.phar results in error

### ISSUE THREAD

**Issue by c33s** [Codegyre/Robo#261]
with Symfony version 2.3.37 running `php robo.phar` having the following `RoboFile.php` works without problems:

```
<?php

class RoboFile extends \Robo\Tasks
{
    public function hello($world)
    {
        $this->say("Hello, $world");
    }
}
```
but when adding the composer autoload

```
<?php
require_once __DIR__.'/vendor/autoload.php';

class RoboFile extends \Robo\Tasks
{
    public function hello($world)
    {
        $this->say("Hello, $world");
    }
}
```

it results in the following error:
```
[InvalidArgumentException]
  Unsupported format "Array".

ERROR: Array to string conversion
in vendor\symfony\symfony\src\Symfony\Component\Console\Helper\DescriptorHelper.php:65
```
dumping `$options` in `DescriptorHelper.php`
```
public function describe(OutputInterface $output, $object, $format = null, $raw = false, $namespace = null)
{
	$options = array('raw_text' => $raw, 'format' => $format ?: 'txt', 'namespace' => $namespace);
	$type = !$raw && 'txt' === $options['format'] ? OutputInterface::OUTPUT_NORMAL : OutputInterface::OUTPUT_RAW;

	
	var_dump($options);
	if (!isset($this->descriptors[$options['format']])) {
		throw new \InvalidArgumentException(sprintf('Unsupported format "%s".', $options['format']));
	}

	$descriptor = $this->descriptors[$options['format']];

	$output->writeln($descriptor->describe($object, $options), $type);
}
```
shows that there is an array in the array
```
`array(3) {
  ["raw_text"]=>
  bool(false)
  ["format"]=>
  array(3) {
    ["format"]=>
    string(3) "txt"
    ["raw_text"]=>
    bool(false)
    ["namespace"]=>
    NULL
  }
  ["namespace"]=>
  NULL
}
```

**Comment by greg-1-anderson** [comment]
The problem you are having is that you cannot load your own autoload file, because [Robo already loads an autoload file](https://github.com/Codegyre/Robo/blob/master/robo#L7) when it starts up. While Composer does allow multiple autload files to be included as a general capability, in practice this does not work if the two projects in question contain incompatible components.

The solution is to `require` Robo from your application, and then run the Robo executable found at `vendor/bin`. If you do this, then Robo will load your application's autoload file, and all will be well.

**Comment by greg-1-anderson** [comment]
See also #263; changes to support Symfony 3 could potentially introduce problems for Symfony 2 (but not necessarily).
